version: '3.8'

services:
  postgres-db:
    image: pgvector/pgvector:pg16
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: pg123456 # 同样替换我
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    container_name: ai-traveler-redis
    # 开启AOF持久化，已移除 --requirepass 参数
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
volumes:
  postgres-data:
    name: pg-data